{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "50d7dc4a-07a0-44ae-8989-9b8f0554018c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "os.environ[\"MONGO_URI_LINK\"] = \"mongodb+srv://prateeks1110:recommend@recommendationdata.uywtlek.mongodb.net/?retryWrites=true&w=majority&appName=recommendationData\"\n",
    "os.environ[\"RAPID_API\"] = \"fab2b40e30mshc7cdf58692c078cp18fd7fjsnb4f1c43f3057\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "f191b491-4c0e-4cd4-9945-e54c3614ce38",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ðŸŸ¢ extraction.py loaded\n",
      "Model file exists: True\n",
      "RAPID_API: fab2b40e30mshc7cdf58692c078cp18fd7fjsnb4f1c43f3057\n",
      "/Users/prateeksharma/Documents/Genre Prediction/server/API/extract_song_feature_links.py:22: UserWarning: [11:17:45] WARNING: /Users/runner/work/xgboost/xgboost/src/gbm/../common/error_msg.h:82: If you are loading a serialized model (like pickle in Python, RDS in R) or\n",
      "configuration generated by an older version of XGBoost, please export the model by calling\n",
      "`Booster.save_model` from that version first, then load it back in current version. See:\n",
      "\n",
      "    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html\n",
      "\n",
      "for more details about differences between saving model and serializing.\n",
      "\n",
      "  model = pickle.load(f)\n",
      "âœ… Model loaded successfully\n",
      "ðŸŸ¢ recommendation.py loaded\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/bin/uvicorn\", line 8, in <module>\n",
      "    sys.exit(main())\n",
      "             ^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/click/core.py\", line 1157, in __call__\n",
      "    return self.main(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/click/core.py\", line 1078, in main\n",
      "    rv = self.invoke(ctx)\n",
      "         ^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/click/core.py\", line 1434, in invoke\n",
      "    return ctx.invoke(self.callback, **ctx.params)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/click/core.py\", line 783, in invoke\n",
      "    return __callback(*args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/main.py\", line 413, in main\n",
      "    run(\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/main.py\", line 580, in run\n",
      "    server.run()\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/server.py\", line 66, in run\n",
      "    return asyncio.run(self.serve(sockets=sockets))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"uvloop/loop.pyx\", line 1518, in uvloop.loop.Loop.run_until_complete\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/server.py\", line 70, in serve\n",
      "    await self._serve(sockets)\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/server.py\", line 77, in _serve\n",
      "    config.load()\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/config.py\", line 435, in load\n",
      "    self.loaded_app = import_from_string(self.app)\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/importer.py\", line 19, in import_from_string\n",
      "    module = importlib.import_module(module_str)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"/Users/prateeksharma/Documents/Genre Prediction/server/API/main.py\", line 3, in <module>\n",
      "    from api_pipeline import run_pipeline\n",
      "  File \"/Users/prateeksharma/Documents/Genre Prediction/server/API/api_pipeline.py\", line 4, in <module>\n",
      "    from recommendation_pipeline import new_song_recommendations\n",
      "  File \"/Users/prateeksharma/Documents/Genre Prediction/server/API/recommendation_pipeline.py\", line 15, in <module>\n",
      "    client = MongoClient(MONGO_URI)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py\", line 884, in __init__\n",
      "    self._get_topology()  # type: ignore[unused-coroutine]\n",
      "    ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py\", line 1716, in _get_topology\n",
      "    self._resolve_srv()\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py\", line 903, in _resolve_srv\n",
      "    res = uri_parser._parse_srv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/uri_parser.py\", line 163, in _parse_srv\n",
      "    nodes = dns_resolver.get_hosts()\n",
      "            ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/srv_resolver.py\", line 155, in get_hosts\n",
      "    _, nodes = self._get_srv_response_and_hosts(True)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/srv_resolver.py\", line 130, in _get_srv_response_and_hosts\n",
      "    results = self._resolve_uri(encapsulate_errors)\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/srv_resolver.py\", line 124, in _resolve_uri\n",
      "    raise ConfigurationError(str(exc)) from None\n",
      "pymongo.errors.ConfigurationError: The DNS query name does not exist: _mongodb._tcp.recommendationdata.uywtlek.mongodb.net.\n"
     ]
    }
   ],
   "source": [
    "!uvicorn main:app --port 2020"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d004cf19-be93-4204-840c-cea9ea09f1f7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
