{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ab626b86-05ef-4e5c-bffe-ff57a4decbf1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[32mINFO\u001b[0m:     Will watch for changes in these directories: ['/Users/prateeksharma/Documents/Genre Prediction/server/API']\n",
      "\u001b[32mINFO\u001b[0m:     Uvicorn running on \u001b[1mhttp://127.0.0.1:8080\u001b[0m (Press CTRL+C to quit)\n",
      "\u001b[32mINFO\u001b[0m:     Started reloader process [\u001b[36m\u001b[1m22679\u001b[0m] using \u001b[36m\u001b[1mWatchFiles\u001b[0m\n",
      "Process SpawnProcess-1:\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/anaconda3/lib/python3.12/multiprocessing/process.py\", line 314, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/opt/anaconda3/lib/python3.12/multiprocessing/process.py\", line 108, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/_subprocess.py\", line 80, in subprocess_started\n",
      "    target(sockets=sockets)\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/server.py\", line 66, in run\n",
      "    return asyncio.run(self.serve(sockets=sockets))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/asyncio/runners.py\", line 194, in run\n",
      "    return runner.run(main)\n",
      "           ^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/asyncio/runners.py\", line 118, in run\n",
      "    return self._loop.run_until_complete(task)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"uvloop/loop.pyx\", line 1518, in uvloop.loop.Loop.run_until_complete\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/server.py\", line 70, in serve\n",
      "    await self._serve(sockets)\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/server.py\", line 77, in _serve\n",
      "    config.load()\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/config.py\", line 435, in load\n",
      "    self.loaded_app = import_from_string(self.app)\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/uvicorn/importer.py\", line 19, in import_from_string\n",
      "    module = importlib.import_module(module_str)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
      "  File \"/Users/prateeksharma/Documents/Genre Prediction/server/API/main.py\", line 3, in <module>\n",
      "    from api_pipeline import run_pipeline\n",
      "  File \"/Users/prateeksharma/Documents/Genre Prediction/server/API/api_pipeline.py\", line 4, in <module>\n",
      "    from recommendation_pipeline import new_song_recommendations\n",
      "  File \"/Users/prateeksharma/Documents/Genre Prediction/server/API/recommendation_pipeline.py\", line 21, in <module>\n",
      "    recommendation_data = pd.DataFrame(list(recommendation.find())).drop(\"_id\",axis=1)\n",
      "                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/cursor.py\", line 1284, in __next__\n",
      "    return self.next()\n",
      "           ^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/cursor.py\", line 1260, in next\n",
      "    if len(self._data) or self._refresh():\n",
      "                          ^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/cursor.py\", line 1208, in _refresh\n",
      "    self._send_message(q)\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/cursor.py\", line 1102, in _send_message\n",
      "    response = client._run_operation(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/_csot.py\", line 119, in csot_wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py\", line 1896, in _run_operation\n",
      "    return self._retryable_read(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py\", line 2005, in _retryable_read\n",
      "    return self._retry_internal(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/_csot.py\", line 119, in csot_wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py\", line 1972, in _retry_internal\n",
      "    ).run()\n",
      "      ^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py\", line 2709, in run\n",
      "    return self._read() if self._is_read else self._write()\n",
      "           ^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py\", line 2854, in _read\n",
      "    self._server = self._get_server()\n",
      "                   ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py\", line 2802, in _get_server\n",
      "    return self._client._select_server(\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py\", line 1791, in _select_server\n",
      "    server = topology.select_server(\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/topology.py\", line 409, in select_server\n",
      "    server = self._select_server(\n",
      "             ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/topology.py\", line 387, in _select_server\n",
      "    servers = self.select_servers(\n",
      "              ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/topology.py\", line 294, in select_servers\n",
      "    server_descriptions = self._select_servers_loop(\n",
      "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/opt/anaconda3/lib/python3.12/site-packages/pymongo/synchronous/topology.py\", line 344, in _select_servers_loop\n",
      "    raise ServerSelectionTimeoutError(\n",
      "pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 680a06f29ae4bf8c6e0224a9, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>\n"
     ]
    }
   ],
   "source": [
    "!uvicorn main:app --reload --port 8080"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "952c909c-644a-4095-8738-ee15dd7994d0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
